<?php

namespace Container0n8uUAI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EventService' shared autowired service.
     *
     * @return \App\Service\EventService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EventService.php';

        return $container->privates['App\\Service\\EventService'] = new \App\Service\EventService(($container->privates['App\\Repository\\CalendarRepository'] ?? $container->load('getCalendarRepositoryService')), ($container->privates['App\\Repository\\PurchaseItemRepository'] ?? $container->load('getPurchaseItemRepositoryService')));
    }
}
