<?php

namespace Container09vufx7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_HVCCyUeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.HVCCyUe' shared service.
     *
     * @return \App\Controller\CategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ActivitieController::filterPrice()": the $categoryRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CategoryRepository". Did you forget to add a use statement?');
    }
}
