<?php

namespace Container09vufx7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ICcbzoUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ICcbzoU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ICcbzoU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activitie' => ['privates', 'App\\Entity\\Activitie', 'getActivitieService', false],
            'activitieRepository' => ['privates', 'App\\Repository\\ActivitieRepository', 'getActivitieRepositoryService', false],
            'purchaseItemRepository' => ['privates', 'App\\Repository\\PurchaseItemRepository', 'getPurchaseItemRepositoryService', true],
        ], [
            'activitie' => 'App\\Entity\\Activitie',
            'activitieRepository' => 'App\\Repository\\ActivitieRepository',
            'purchaseItemRepository' => 'App\\Repository\\PurchaseItemRepository',
        ]);
    }
}
