<?php

namespace Container2ItE7iB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YL314sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yL31_4s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yL31_4s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activity' => ['privates', 'App\\Entity\\Activity', 'getActivityService', false],
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'sendMailService' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
        ], [
            'activity' => 'App\\Entity\\Activity',
            'dispatcher' => '?',
            'sendMailService' => 'App\\Service\\SendMailService',
        ]);
    }
}
