<?php

namespace ContainerOGRfbeN;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AmWXhMLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AmWXhML' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AmWXhML'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarRepository' => ['privates', 'App\\Repository\\CalendarRepository', 'getCalendarRepositoryService', true],
            'category' => ['privates', '.errored..service_locator.AmWXhML.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.AmWXhML": it references class "App\\Entity\\Category" but no such service exists.'],
            'generateLinkExtension' => ['privates', 'App\\Twig\\GenerateLinkExtension', 'getGenerateLinkExtensionService', false],
        ], [
            'calendarRepository' => 'App\\Repository\\CalendarRepository',
            'category' => 'App\\Entity\\Category',
            'generateLinkExtension' => 'App\\Twig\\GenerateLinkExtension',
        ]);
    }
}
