<?php

namespace ContainerX1E1RbI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FcIuHHbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FcIuHHb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FcIuHHb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', false],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'activityRepository' => 'App\\Repository\\ActivityRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
        ]);
    }
}
