<?php

namespace ContainerL3NNHHP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FGQAdtyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fGQAdty' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fGQAdty'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'purchaseItem' => ['privates', '.errored..service_locator.fGQAdty.App\\Entity\\PurchaseItem', NULL, 'Cannot autowire service ".service_locator.fGQAdty": it references class "App\\Entity\\PurchaseItem" but no such service exists.'],
            'purchaseItemRepository' => ['privates', 'App\\Repository\\PurchaseItemRepository', 'getPurchaseItemRepositoryService', true],
        ], [
            'em' => '?',
            'purchaseItem' => 'App\\Entity\\PurchaseItem',
            'purchaseItemRepository' => 'App\\Repository\\PurchaseItemRepository',
        ]);
    }
}
