<?php

namespace ContainerL3NNHHP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fGQAdty.App\Entity\PurchaseItem' shared service.
     *
     * @return \App\Entity\PurchaseItem
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fGQAdty": it references class "App\\Entity\\PurchaseItem" but no such service exists.');
    }
}
