<?php

namespace ContainerL3NNHHP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaffSchedule2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ucsB0dg.App\Entity\StaffSchedule' shared service.
     *
     * @return \App\Entity\StaffSchedule
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ucsB0dg": it references class "App\\Entity\\StaffSchedule" but no such service exists.');
    }
}
