<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEB1Zu68\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEB1Zu68/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEB1Zu68.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEB1Zu68\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEB1Zu68\App_KernelDevDebugContainer([
    'container.build_hash' => 'EB1Zu68',
    'container.build_id' => 'ea50633f',
    'container.build_time' => 1706612485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEB1Zu68');
