<?php

namespace ContainerCRPzHJB;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaff2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Iowt0uw.App\Entity\Staff' shared service.
     *
     * @return \App\Entity\Staff
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Iowt0uw": it references class "App\\Entity\\Staff" but no such service exists.');
    }
}
