<?php

namespace ContainerEB1Zu68;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BEg0U4JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BEg0U4J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BEg0U4J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sendMailService' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'sendMailService' => 'App\\Service\\SendMailService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
