<?php

namespace ContainerHJoYQ3h;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DYX9QWRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DYX9QWR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DYX9QWR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activitieRepository' => ['privates', 'App\\Repository\\ActivitieRepository', 'getActivitieRepositoryService', false],
            'categoryRepository' => ['privates', '.errored.XiMD_sG', NULL, 'Cannot determine controller argument for "App\\Controller\\ActivitieController::listActivitieByCatamaran()": the $categoryRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CategoryRepository". Did you forget to add a use statement?'],
        ], [
            'activitieRepository' => 'App\\Repository\\ActivitieRepository',
            'categoryRepository' => '?',
        ]);
    }
}
