<?php

namespace ContainerHJoYQ3h;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WS5E7F4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WS5E7F4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WS5E7F4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activitieRepository' => ['privates', 'App\\Repository\\ActivitieRepository', 'getActivitieRepositoryService', false],
            'formatdateService' => ['privates', 'App\\Service\\Formatdate', 'getFormatdateService', true],
        ], [
            'activitieRepository' => 'App\\Repository\\ActivitieRepository',
            'formatdateService' => 'App\\Service\\Formatdate',
        ]);
    }
}
