<?php

namespace ContainerHJoYQ3h;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitieSettingsRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ActivitieSettingsRepository' shared autowired service.
     *
     * @return \App\Repository\ActivitieSettingsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ActivitieSettingsRepository.php';

        return $container->privates['App\\Repository\\ActivitieSettingsRepository'] = new \App\Repository\ActivitieSettingsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
