<?php

namespace ContainerSRSWuVr;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KTAPlHcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KTAPlHc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KTAPlHc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendar' => ['privates', '.errored..service_locator.KTAPlHc.App\\Entity\\Calendar', NULL, 'Cannot autowire service ".service_locator.KTAPlHc": it references class "App\\Entity\\Calendar" but no such service exists. You should maybe alias this class to the existing "App\\Entity\\Activity" service.'],
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'sendMailService' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
        ], [
            'calendar' => 'App\\Entity\\Calendar',
            'dispatcher' => '?',
            'sendMailService' => 'App\\Service\\SendMailService',
        ]);
    }
}
