<?php

namespace Container2M917Bu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6xxNycQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6xxNycQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6xxNycQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartService' => ['privates', 'App\\Service\\CartService', 'getCartServiceService', false],
            'formatdate' => ['privates', 'App\\Service\\Formatdate', 'getFormatdateService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'cartService' => 'App\\Service\\CartService',
            'formatdate' => 'App\\Service\\Formatdate',
            'security' => '?',
        ]);
    }
}
