<?php

namespace Container2M917Bu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8D0GUWzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8D0GUWz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8D0GUWz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'staff' => ['privates', '.errored..service_locator.8D0GUWz.App\\Entity\\Staff', NULL, 'Cannot autowire service ".service_locator.8D0GUWz": it references class "App\\Entity\\Staff" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'staff' => 'App\\Entity\\Staff',
        ]);
    }
}
