#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_agenda_by_category:
    path: '/agenda/{categoryTitle}'
    controller: 'App\Controller\AgendaByCategoryController::renderAgendaByCategory'


