<?php

namespace Container9sSUdBD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EHXQlqWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eHXQlqW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eHXQlqW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService', false],
            'calendarRepository' => ['privates', 'App\\Repository\\CalendarRepository', 'getCalendarRepositoryService', true],
            'formatdateService' => ['privates', 'App\\Service\\Formatdate', 'getFormatdateService', true],
            'staffScheduleRepository' => ['privates', 'App\\Repository\\StaffScheduleRepository', 'getStaffScheduleRepositoryService', true],
        ], [
            'activityRepository' => 'App\\Repository\\ActivityRepository',
            'calendarRepository' => 'App\\Repository\\CalendarRepository',
            'formatdateService' => 'App\\Service\\Formatdate',
            'staffScheduleRepository' => 'App\\Repository\\StaffScheduleRepository',
        ]);
    }
}
