<?php

namespace Container39RUDws;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QnjRarBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QnjRarB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QnjRarB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorySetting' => ['privates', '.errored..service_locator.QnjRarB.App\\Entity\\CategorySetting', NULL, 'Cannot autowire service ".service_locator.QnjRarB": it references class "App\\Entity\\CategorySetting" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categorySetting' => 'App\\Entity\\CategorySetting',
            'entityManager' => '?',
        ]);
    }
}
