<?php

namespace Container5VsTdrp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2PXzERC.App\Entity\Calendar' shared service.
     *
     * @return \App\Entity\Calendar
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.2PXzERC": it references class "App\\Entity\\Calendar" but no such service exists. You should maybe alias this class to the existing "App\\Entity\\Activity" service.');
    }
}
