<?php

namespace ContainerJAoZZ27;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__GpCLsYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..GpCLsY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..GpCLsY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', false],
            'generateLinkExtension' => ['privates', 'App\\Twig\\GenerateLinkExtension', 'getGenerateLinkExtensionService', false],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'generateLinkExtension' => 'App\\Twig\\GenerateLinkExtension',
        ]);
    }
}
