<?php

namespace ContainerXEYTyGd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BZHX9kmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bZHX9km' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bZHX9km'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Activity' => ['privates', 'App\\Entity\\Activity', 'getActivityService', false],
        ], [
            'Activity' => 'App\\Entity\\Activity',
        ]);
    }
}
