<?php

namespace ContainerVuQWv5L;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BU1nIZFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bU1nIZF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bU1nIZF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'purchaseRepository' => ['privates', 'App\\Repository\\PurchaseRepository', 'getPurchaseRepositoryService', true],
            'sendMailService' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
            'user' => ['privates', '.errored..service_locator.bU1nIZF.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.bU1nIZF": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'purchaseRepository' => 'App\\Repository\\PurchaseRepository',
            'sendMailService' => 'App\\Service\\SendMailService',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
