<?php

namespace ContainerVuQWv5L;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YR7DKzyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YR7DKzy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YR7DKzy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'staffScheduleSettingsRepository' => ['privates', 'App\\Repository\\StaffScheduleSettingsRepository', 'getStaffScheduleSettingsRepositoryService', true],
        ], [
            'staffScheduleSettingsRepository' => 'App\\Repository\\StaffScheduleSettingsRepository',
        ]);
    }
}
