<?php

namespace ContainerVuQWv5L;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_UMAW1RkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.UMAW1Rk' shared service.
     *
     * @return \App\Controller\Admin\Calendar
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Admin\\AdminCalendarAddUserQuantityController::calendarAddUserQuantity()": the $calendar argument is type-hinted with the non-existent class or interface: "App\\Controller\\Admin\\Calendar". Did you forget to add a use statement?');
    }
}
