<?php

namespace ContainerJu5CZ3J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitie2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nYdzAk1.App\Entity\Activitie' shared service.
     *
     * @return \App\Entity\Activitie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nYdzAk1": it references class "App\\Entity\\Activitie" but no such service exists.');
    }
}
