<?php

namespace ContainerNNSNdo7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorySetting2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qFIPDCn.App\Entity\CategorySetting' shared service.
     *
     * @return \App\Entity\CategorySetting
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qFIPDCn": it references class "App\\Entity\\CategorySetting" but no such service exists.');
    }
}
