<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9sSUdBD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9sSUdBD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9sSUdBD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9sSUdBD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9sSUdBD\App_KernelDevDebugContainer([
    'container.build_hash' => '9sSUdBD',
    'container.build_id' => '92090f77',
    'container.build_time' => 1706875673,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9sSUdBD');
