<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNSNdo7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNSNdo7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNSNdo7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNSNdo7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNNSNdo7\App_KernelDevDebugContainer([
    'container.build_hash' => 'NNSNdo7',
    'container.build_id' => 'b198d48e',
    'container.build_time' => 1707074945,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNSNdo7');
