<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container39RUDws\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container39RUDws/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container39RUDws.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container39RUDws\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container39RUDws\App_KernelDevDebugContainer([
    'container.build_hash' => '39RUDws',
    'container.build_id' => '1bc70ed9',
    'container.build_time' => 1706302911,
], __DIR__.\DIRECTORY_SEPARATOR.'Container39RUDws');
