<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_a-constructor_js-node_modules_core-js_internals_array--ebd428.js',
                '/build/vendors-node_modules_hotwired_turbo-rails_app_javascript_turbo_index_js-node_modules_symfony_-5bc1c2.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/assets_styles_app_css-assets_styles_style_css.css',
            ],
        ],
        'user' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_a-constructor_js-node_modules_core-js_internals_array--ebd428.js',
                '/build/vendors-node_modules_core-js_modules_es_array_concat_js-node_modules_core-js_modules_es_array-e643a4.js',
                '/build/user.js',
            ],
            'css' => [
                '/build/assets_styles_app_css-assets_styles_style_css.css',
            ],
        ],
    ],
],

]];
